package cfg.enums;

public enum RestResponse {
	INSERIR, REMOVER, ALTERAR,
	SELECIONAR_ERROR, INSERIR_ERROR,
	REMOVER_ERROR, ALTERAR_ERROR, LOGIN_ERRO,
	SEM_AUTORIZACAO, EMAIL_EM_USO_ERROR, NOME_JA_CADASTRADO,
	MATRICULA_USO_ERROR, EMAIL_NAO_ENCONTRADO, ERRO_ENVIAR_EMAIL,
	EMAIL_ENVIADO_SUCESSO, EMAIL_ERRADO, USUARIO_JA_CADASTRADO,
	IMPOSSIVEL_REATIVAR
}
